### ISSUE TITLE
no recalc on error correction

### ISSUE THREAD

**Issue by declann** [keenbug/tables#5]
Hi Daniel,

The following works:

![image](https://github.com/keenbug/ReSheet/assets/353214/d2750b93-3ffa-4c95-a9db-51fbfdff0a89)

and if I update to 1+2 both answers update.

But if I do this in a different order and cause an error:

![image](https://github.com/keenbug/ReSheet/assets/353214/5e6604c9-ca69-4f8d-9897-fd12a27eee7a)

then when I correct by assigning to 'a' in the top calc, there is no update

![image](https://github.com/keenbug/ReSheet/assets/353214/d3d21543-3648-48e5-89dc-e06d126259d3)

Remove the cell and re-creating the same thing is a workaround. Not sure how broad this is.

Regards
Declan

**Comment by keenbug** [comment]
Thanks Declan!
